apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "coredns"
  namespace: "kube-system"
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        k8s_external k8s.askov.net
        hosts /etc/coredns/NodeHosts {
          ttl 60
          reload 15s
          fallthrough
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
        import /etc/coredns/custom/*.override
    }
    import /etc/coredns/custom/*.server
  NodeHosts: |
    192.168.4.4 k8smaster1.k8s.askov.net
    192.168.4.10 k8snode1.k8s.askov.net
    192.168.4.20 k8snode2.k8s.askov.net
