apiVersion: v1
kind: Service
metadata:
  name: ext-dns
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: "DNS"
    metallb.universe.tf/loadBalancerIPs: 192.168.32.1
spec:
  type: LoadBalancer
  ports:
    - name: dns
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
  selector:
    k8s-app: kube-dns