---

- name: Check k3s version
  shell:
    cmd: "/usr/local/bin/k3s --version | grep -F '{{ k3s_version }}'"
  register: k3s_version_ok
  changed_when: false
  failed_when: false

- name: Install/update k3s
  when: k3s_version_ok.rc != 0
  block:
    - name: Upload K3s config files
      template:
        src: "{{ item }}"
        dest: "/etc/rancher/k3s/"
        mode: 0644
      with_fileglob:
        - "templates/etc/rancher/k3s/*"

    - name: Install/update k3s
      shell:
        cmd: "curl -sfL https://get.k3s.io | 
          INSTALL_K3S_EXEC='server'
          INSTALL_K3S_VERSION='{{ k3s_version }}'
          sh -"