apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: metallb-advertisment
  namespace: metallb-system
spec:
  ipAddressPools:
    - metallb-pool # Reference to the IP Address Pool above
  localPref: 100 # Weight of the routes we advertise
  communities:
    - 65535:65282 # no-advertise community