apiVersion: v1
kind: Service
metadata:
  name: ext-dns-udp
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: "DNS"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.14.5
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
    - port: 53
      targetPort: 53
      protocol: TCP
  selector:
    k8s-app: kube-dns